name: 'Release'
description: 'Create github releases'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  packageNamespace:
    description: >
      A string value that is namespace of package
    default: ''
  lastCommitMessage:
    description: >
      Last commit message
    default: ${{ github.event.head_commit.message }}
  slackToken:
    description: >
      Slack token
  slackChannel:
    description: >
      Slack channel
outputs:
  released:
    description: >
      A boolean value that can be checked whether a released or not.
  releasedTags:
    description: >
      A JSON array that the released tags.
      (e.g. ["www-1.210527.0", "swift-1.210527.1"])

runs:
  using: 'node12'
  main: 'dist/index.js'
